project:
  title: "ingredient_analysis"
  execute-dir: project
  output-dir: results
editor: source
format:
  html:
    toc: true
    css: styles.css
    theme:
      dark: darkly
      light: flatly
